name: kollibry
description: "E-commerce app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  get_storage: ^2.1.1
  get: ^4.6.6
  badges: ^2.0.3
  flutter_dotenv: ^5.1.0

  # Utility Packages
  http: ^1.2.2
  intl: ^0.20.1
  logger: ^2.5.0
  flutter_svg: ^2.0.16
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.3
  smooth_page_indicator: ^1.2.0+3
  motion_tab_bar: ^2.0.0
  carousel_slider: ^5.0.0

  # data
  firebase_core: ^3.10.0
  image_picker: ^1.1.2

  flutter_map: ^8.0.0
  permission_handler: ^11.3.1
  latlong2: ^0.9.1
  location: ^8.0.0
  flutter_map_tile_caching: ^10.1.0
  dio: ^5.8.0+1

  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/images/
      - assets/logos/
      - assets/images/banners/
      - assets/images/category/
      - assets/images/products/
      - assets/images/drone/

